[package]
authors = ["Zhan Ganiev <zhan.boolean@icloud.com>"]
name = "contract-public-key-delegation"
version = "0.1.0"
edition = "2018"

[dependencies]
contract-utils = {path = "../utils/contract-utils"}
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "contract_public_key_delegation"
path = "src/contract_public_key_delegation.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std"]